### PR TITLE
Update unit tests to run different variations of the Stack Trace tests.

### PR DESCRIPTION
**Pull request by jeffmiles63**
- Changed TestStackTrace.cpp to compile separate google test
    - Add ASSERT_DEATH logic to handle terminate cases. 
    - Run program with gtest_filter to control which case is run and verified
- Update Make file to compile and run Normal and Terminate  and rdynamic stack trace test
- Update CMake to compile and run Normal and Terminate and rdynamic stack trace test
Had to make changes to KOKKOS_ADD_TEST...in cmake/fake_tribits.cmake
Added logic in CMakelists.txt for unit_tests to look use different filter if rdynamic is enabled

### CODE REVIEW

**Comment by masterleinad** [comment]
You should be able to directly push to this branch.

**Comment by jeffmiles63** [comment]
Git says I don’t have write access ☹


@ibaned @crtrott @dalg24 @masterleinad

**Comment by dalg24** [comment]
You definitely do have permissions.  GH reports that you forced-push to the branch 7 days ago.

**Comment by dalg24** [comment]
```
@jeffmiles63 jeffmiles63 force-pushed the ibaned:new-stacktrace  branch from ac1bdc8 to a257bfd 7 days ago
```

**Pull request merged**
